package com.blockoutlines.addon.modules;

import com.blockoutlines.addon.BlockOutlinesAddon;
import com.blockoutlines.addon.mixin.GameRendererInvoker;
import meteordevelopment.meteorclient.events.game.GameLeftEvent;
import meteordevelopment.meteorclient.events.world.TickEvent;
import meteordevelopment.meteorclient.settings.DoubleSetting;
import meteordevelopment.meteorclient.settings.Setting;
import meteordevelopment.meteorclient.settings.SettingGroup;
import meteordevelopment.meteorclient.systems.modules.Module;
import meteordevelopment.orbit.EventHandler;
import net.minecraft.util.Identifier;

/**
 * Color grading for the whole game world (saturation, contrast, brightness). It uses a vanilla post effect, which
 * is applied before the GUI is drawn, so menus, chat and the hotbar keep their normal colors.
 * The post effects are generated by tools/gen_post_effects.py, so values snap to small steps.
 */
public class ColorGrading extends Module {
    private final SettingGroup sgGeneral = settings.getDefaultGroup();

    public final Setting<Double> saturation = sgGeneral.add(new DoubleSetting.Builder()
        .name("saturation")
        .description("1 is normal, 0 is black and white, higher is more vivid. Steps of 0.25.")
        .defaultValue(1.3)
        .range(0.0, 3.0)
        .sliderRange(0.0, 3.0)
        .build()
    );

    public final Setting<Double> contrast = sgGeneral.add(new DoubleSetting.Builder()
        .name("contrast")
        .description("1 is normal. Steps of 0.25.")
        .defaultValue(1.0)
        .range(0.5, 1.5)
        .sliderRange(0.5, 1.5)
        .build()
    );

    public final Setting<Double> brightness = sgGeneral.add(new DoubleSetting.Builder()
        .name("brightness")
        .description("0 is normal. Steps of 0.1.")
        .defaultValue(0.0)
        .range(-0.2, 0.2)
        .sliderRange(-0.2, 0.2)
        .build()
    );

    public ColorGrading() {
        super(BlockOutlinesAddon.CATEGORY, "color-grading", "Changes saturation, contrast and brightness of the game world without touching the GUI.");
    }

    @Override
    public void onDeactivate() {
        clear();
    }

    @EventHandler
    private void onGameLeft(GameLeftEvent event) {
        clear();
    }

    @EventHandler
    private void onTick(TickEvent.Post event) {
        if (mc.world == null || mc.gameRenderer == null) return;
        int s = clamp((int) Math.round(saturation.get() / 0.25), 0, 12);
        int c = clamp((int) Math.round((contrast.get() - 0.5) / 0.25), 0, 4);
        int b = clamp((int) Math.round((brightness.get() + 0.2) / 0.1), 0, 4);
        // Set every tick: vanilla resets the post effect when the camera entity changes (joining a world, respawning...).
        ((GameRendererInvoker) mc.gameRenderer).blockoutlines$setPostProcessor(Identifier.of("blockoutlines", String.format("grade_%02d_%d_%d", s, c, b)));
    }

    private static int clamp(int v, int lo, int hi) {
        return Math.max(lo, Math.min(hi, v));
    }

    private void clear() {
        if (mc.gameRenderer != null) ((GameRendererInvoker) mc.gameRenderer).blockoutlines$clearPostProcessor();
    }
}
